### ISSUE TITLE
Add a test driver that supports the Method of Manufactured Solutions (MMS)

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#104]
To date, our CI testing doesn't actually verify any of our computed solutions. It would be nice if we could verify that RDycore's computed solutions converge at the expected rates, since the convergence rate is one of the most effective measures of correctness. It would certainly make me more confident about code changes!

@bishtgautam and I briefly discussed the possibility of putting together a test driver that accepts a special input format designed to accommodate MMS tests. Depending on the complexity of the desired tests, we could make it very easy to set up these tests by using tools that parse math expressions from text (like [tinyexpr](https://github.com/codeplea/tinyexpr)).

I don't know enough about what the science team has been investigating with MMS to draft a proposal. Gautam, if you know of materials and can link me to them, I could start thinking about this.

## TODO
- [x] Clean up some `RDySetup` code to make it easier for the main library and the MMS driver to share some things
- [x] Implement `mms` section parsing
- [x] Create `RDySetupMMS` as an alternative to `RDySetup` (in `mms.c`)
  - [x] analytic initial conditions
  - [x] analytic boundary conditions
  - [x] analytic sources
  - [x] analytic material properties (including those in source terms)
- [x] Update the `mms` driver to use the new system
- [x] provide a mechanism for convergence testing

**Comment by jeff-cohere** [comment]
I did find [an ex2b_MMS.c](https://github.com/RDycore/toy-problems/blob/dongyu/MMS/swe/ex2b_MMS.c) file in the `toy-problems` repo.

**Comment by knepley** [comment]
@jeff-cohere I recommend `muparser` for getting the functions. I have used it before, PETSc can build it automatically, and it is used in other projects.

**Comment by bishtgautam** [comment]
@fdongyu has been undertaking model verification via:
1. MMS, and
2. Comparision against analytical solutions of SWE for multiple problems from https://hal.science/hal-00628246/file/SW_analytic-complements.pdf

Some information about the timeline. Over the next month, we will have multiple verification problems (~7) completed in the `toy-problems` repo. Then, we will start migrating those verification problems into RDycore repo and at that stage, we will be ready to start developing a verification driver.

**Comment by bishtgautam** [comment]
Here is the link to our internal confluence page created by @fdongyu summarizing the validation problems for RDycore https://rdycore.atlassian.net/wiki/spaces/PD/pages/85458945/Flow+RDycore+validation+problems

**Comment by jeff-cohere** [comment]
Here's what I'm thinking of doing to the existing MMS driver to make it easier to define different problems. Using [muparser](https://beltoforion.de/en/muparser/) (which I've confirmed can be downloaded and built by PETSc as @knepley mentioned), we can add support for functions in an MMS-specific YAML section that is parsed only by the MMS driver. Here's how "problem 1" in the existing MMS driver might look in such a setup.

```
# this section contains analytic forms for the method of manufactured solutions
mms:
  constants:
    h0: 1
    z0: 1
    n0: 1
  functions: # functions of x, y, t (non-normalized units)
    # water height
    h:    h0 * (1 + sin(x)*sin(y)) * exp(t)
    dhdx: h0 * exp(t) * sin(y) * cos(x)
    dhdy: h0 * exp(t) * sin(x) * cos(y)
    dhdt: h0 * (1 + sin(x)*sin(y)) * exp(t)

    # x velocity
    u:     u0 * cos(x) * sin(y) * exp(t)
    dudx: -u0 * sin(x) * sin(y) * exp(t)
    dudy:  u0 * cos(x) * cos(y) * exp(t)
    dudt:  u0 * cos(x) * sin(y) * exp(t)

    # y velocity
    v:     v0 * sin(x) * cos(y) * exp(t)
    dvdx:  v0 * cos(x) * cos(y) * exp(t)
    dvdy: -v0 * sin(x) * sin(y) * exp(t)
    dvdt:  v0 * sin(x) * cos(y) * exp(t)

    # (x and y momenta can be evaluated from h(x,y,t) * {u,v}(x,y,t))

    # elevation as z(x, y)
    z:     z0 * sin(x) * sin(y)
    dzdx:  z0 * cos(x) * sin(y)
    dzdy:  z0 * sin(x) * cos(y)

    # source-related term n(x,y)
    n:     n0 * (1 + sin(x) * sin(y))
```

If this works out, it'll be trivial to set up more MMS problems, and we could even explore the use of space- and time-dependent functions in RDycore itself down the line if that's an interesting direction.

**Comment by jeff-cohere** [comment]
Hey @knepley ,

Can you point me at any code that makes use of `PetscConvEst`? I think I have the MMS stuff in the right shape to make use of it.

**Comment by knepley** [comment]
@jeff-cohere Sure! I think the simplest to understand is SNES tutorial ex13, test 2d_p1_conv. You will notice that a comment above the test gives the more expensive settings that are used to get the true convergence rate. The test itself runs fast for CI builds.

It is a little hard to see what you need for ConvEst to work, so I will try to summarize. You need an exact solution so you can evaluate the error, which is set on line 177. If we are just looking at temporal convergence, then this is the only thing you need I think. If we want spatial convergence, then DMRefine() and copying the DS need to setup a complete new problem.

**Comment by knepley** [comment]
Yep. Mail me with any problems, and we can do a Zoom if anything is not making sense.

**Comment by jeff-cohere** [comment]
Excellent, thanks!
